sudo: false
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  submodules: false

install:
  - cp src/config/env.ts.dist src/config/env.ts
  - npm install -g codecov
  - npm install -g yarn
  - yarn

script:
  - yarn test:coverage
  - codecov

branches:
  only:
  - master
  - develop
